# Generated by Django 4.1 on 2022-09-09 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_start', models.CharField(default='', max_length=200)),
                ('lat_start', models.CharField(default='', max_length=200)),
                ('long_end', models.CharField(default='', max_length=200)),
                ('lat_end', models.CharField(default='', max_length=200)),
                ('length', models.CharField(default='', max_length=200)),
                ('speed', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
