# Generated by Django 4.1 on 2022-09-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_segment', '0002_alter_trafficsegment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsegment',
            name='id',
            field=models.BigAutoField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
